# Hugo template via https://github.com/gitpod-io/template-hugo/blob/main/.gitpod.yml
tasks:
  - name: Install and start hugo
    before: brew install hugo
    init: echo "Your version of Hugo is `hugo version`"
    command: hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0 --themesDir ../..
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - port: 1313
    onOpen: open-preview
